apiVersion: v1
kind: Endpoints
metadata:
  name: ana-api
subsets:
  - addresses:
      - ip: 89.168.103.75
    ports:
      - port: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ana-api
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ana-api
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod # Use the ClusterIssuer for Let's Encrypt SSL
spec:
  tls:
    - hosts:
        - api.ana.przemeksosna.pl
      secretName: ana-api-tls # Cert-Manager will create this secret to hold the SSL certificate
  rules:
    - host: api.ana.przemeksosna.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ana-api
                port:
                  number: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ana-frontend
subsets:
  - addresses:
      - ip: 89.168.103.75
    ports:
      - port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ana-frontend
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ana-frontend
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod # Use the ClusterIssuer for Let's Encrypt SSL
spec:
  tls:
    - hosts:
        - ana.przemeksosna.pl
      secretName: ana-frontend-tls # Cert-Manager will create this secret to hold the SSL certificate
  rules:
    - host: ana.przemeksosna.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ana-frontend
                port:
                  number: 5000